services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run pytest tests
    depends_on:
      - api
    cap_add:
      - NET_ADMIN